server {
    listen       8081;
    server_name  _;
    client_max_body_size 100m;
    server_tokens off;
    # 基础请求头缓冲区大小（默认1k，增大到4k）
    client_header_buffer_size 4k;
    # 大请求头的缓冲区（数量4个，每个8k，可根据需求调整）
    large_client_header_buffers 4 8k;

    root   /usr/share/nginx/html;
    index  index.html index.htm;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ^~ /beauty-api {
        proxy_pass http://10.12.18.114:9080;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # 错误页面配置
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}    
